### ISSUE TITLE
Notebooks dir should be a volume

### ISSUE THREAD

**Issue by pikeas** [rothnic/anaconda-notebook#1]
Notebooks should be persistent rather than being destroyed when the container is stopped.

Reference: https://github.com/ipython/docker-notebook/blob/master/notebook/Dockerfile

**Comment by rothnic** [comment]
Part of the intended use for this is with [tmpnb](https://github.com/jupyter/tmpnb), so I wouldn't want to prescribe how the notebooks are stored. With tmpnb, you don't want them persisted at all, instead you'd want to link them in from some other location, like [google drive](https://github.com/jupyter/jupyter-drive), or you are free to use git within the jupyter terminal. The notebooks directory is completely up to the end user really, something that could easily be modified. I was more just providing an example.

I wonder if there is a solution where the directory is an input? I think the volume can be created with the run command. Otherwise, I'd suggest just extending off of this image using "FROM", then making your custom volume changes.

Open to ideas here.

**Comment by ruxi** [comment]
The [docker compose](https://docs.docker.com/compose/yml/) docs suggest it may be possible to set a directory as an input using the volumes option.

**Comment by rothnic** [comment]
Looks like the regular `docker run -v <host directory>:<guest directory>` works without modification to the image. See [docker volumes](https://docs.docker.com/userguide/dockervolumes/) documentation.

For me, this looked like the following command:

```
docker run -i -t -p 8888:8888 -v \
/Users/rothnic/Documents/workspace/notebooks:/home/condauser/notebooks rothnic/anaconda-notebook \
/home/condauser/anaconda3/bin/ipython notebook
```

This is just the regular run command executed by the dockerfile, except I've added the `-v` option. You then provide it the place where your notebooks exist, then `:`, then the place where we expect the notebooks to be in the container.

**Comment by denisvolokh** [comment]
Guys, are you able to save new notebooks because when I mount host directory like in your example I have permisson denied error.
