### ISSUE TITLE
Explain why --net=host is necessary

### ISSUE THREAD

**Issue by pikeas** [rothnic/anaconda-notebook#2]
Docs should explain why the notebook server requires this option, and how things will break if it's omitted.

**Comment by rothnic** [comment]
Thanks for the comment. This was a holdover from starting this effort specifically for tmpnb use, which uses that option.

Since I looked it up, I'll document what the option does. The `--net=host` option pretty much just doesn't containerize the container's networking. So when the Dockerfile does `EXPOSE 8888`, there is no port forwarding to do. Using the `-p 8888:8888` yields the same result. You could also do `-p 9090:8888`, as long as you can reach 9090 on the docker host.

If you are using boot2docker, this means exposing the port on the boot2docker vm in virtualbox, which looks like this:

![](http://i.imgur.com/CFAv2IC.png)
