### ISSUE TITLE
Proxy target missing trying to run image rothnic/anaconda-notebook

### ISSUE THREAD

**Issue by gpillemer** [rothnic/anaconda-notebook#3]
Hi I'm probably doing something wrong. 
I want to get rothnic/anaconda-notebook running as tmpnb. 
I have no prob getting the jupyter/minimal running. 
But getting this to work with the following command is give me a proxy target missing error. 

docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=tmpnb -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image='rothnic/anaconda-notebook' --container_port=8000 --command="ipython notebook --NotebookApp.base_url={base_path} --port {port}"

Could you help me out? I would really love to use this configuration with my team.

**Comment by rothnic** [comment]
Trying it out. I haven't used this in some time, so waiting for things to download again. Take a look at jupyter/tmpnb#125, where I pasted the exact command that I used at one point to get it working.

**Comment by rothnic** [comment]
@gpillemer: this issue cropped up because the command changed, since the base python environment is now using python 3. During image creation, both a python 3 and python 2 conda environment are created and they are hooked into ipython, so you can conda install/pip install into either as you want.

BTW, I have done other work on making this image not so big, so I need to update it at some point.

See the current readme for the exact commands for getting this running with tmpnb.

**Comment by gpillemer** [comment]
Tried it and it works awesomely!
Thanks so much for your help!

G

**Comment by gpillemer** [comment]
Sorry for the hand-holding - but wanting to know if the option to load a
host directory in the docker container, works with the tmpnb run command...?

if so could you perhaps share the command....?

Sorry new to both docker and jupyterhub.
Thanks for your help!

G

**Comment by rothnic** [comment]
Since the tmpnb orchestrator is running the anaconda notebook image, it would have to pass the volume. I don't see that as a current option for tmpnb, so you'd likely need to just extend the anaconda notebook image.

So you would do something like this in a new Dockerfile. The Dockerfile would exist in the same location as a directory of notebooks, called "my_special_notebooks".

```
FROM rothnic/anaconda-notebook

COPY ./my_special_notebooks /home/condauser/notebooks
```

Then, from a command line in this new directory. You'd do:

```
# build your custom version with your own specific tag, using the current directory for source files
docker build -t my-anaconda-notebook .
```

Then, instead of `rothnic/anaconda-notebook`, you'd use your just created image `my-anaconda-notebook`.

**Comment by gpillemer** [comment]
Thanks! This is awesome. Thank you for taking the time.
G
